// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Image/ImageRpc.proto

package com.xuanwu.xtion.grpc.media;

public final class MediaServiceProto {
  private MediaServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024Image/ImageRpc.proto\022\005media\032\022BasicMess" +
      "age.proto\032\026Image/ImageMedia.proto2`\n\014Med" +
      "iaService\022,\n\017checkImageFuzzy\022\n.RpcString" +
      "\032\013.RpcBoolean\"\000\022\"\n\nfetchImage\022\006.Image\032\n." +
      "RpcString\"\000B8\n\033com.xuanwu.xtion.grpc.med" +
      "iaB\021MediaServiceProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xuanwu.xtion.grpc.message.BasicMessageProto.getDescriptor(),
          com.xuanwu.xtion.grpc.message.image.ImageMediaProto.getDescriptor(),
        }, assigner);
    com.xuanwu.xtion.grpc.message.BasicMessageProto.getDescriptor();
    com.xuanwu.xtion.grpc.message.image.ImageMediaProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
